### ISSUE TITLE
Unterminated string starting at: line 1 column 23

### ISSUE THREAD

**Issue by bmbariah** [RoosDaniel/SafetyNet-Attestation#1]
When trying to do a verify_offline it gives the above error.
Can you maybe give a sample?

Thanks.

Full Logs`Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "/home/runner/.local/lib/python3.6/site-packages/safetynet_attestation/Attestation.py", line 132, in verify_offline
    self.header = self._get_json_at_index(index=0)
  File "/home/runner/.local/lib/python3.6/site-packages/safetynet_attestation/Attestation.py", line 52, in _get_json_at_index
    return json.loads(base64.b64decode(data).decode())
  File "/usr/local/lib/python3.6/json/__init__.py", line354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 23 (char 22)`

**Comment by bmbariah** [comment]
Nevermind. 
That JWT string is very long such that Android Studio couldn't display it in full.
